# Generated by Django 3.2.3 on 2021-06-22 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='portfolio',
            new_name='portfolio_model',
        ),
    ]
