# Generated by Django 3.2.3 on 2021-06-22 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_portfolio_model_portfolio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='portfolio',
            new_name='app_model',
        ),
    ]
