# Generated by Django 3.2.3 on 2021-06-22 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_portfolio_app_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='app_model',
            new_name='portfolio_model',
        ),
    ]
