# Generated by Django 3.2.3 on 2021-06-22 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_app_model_portfolio_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='portfolio_model',
            new_name='portfolio_records',
        ),
    ]
