# Generated by Django 3.2.3 on 2021-06-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_portfolio_model_portfolio_records'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='portfolio_records',
            new_name='Project',
        ),
    ]
